# Generated by Django 3.0.5 on 2020-04-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200421_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='banner_image',
            field=models.ImageField(default=None, upload_to='banner_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='discount_images'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='slug',
            field=models.SlugField(),
        ),
    ]
